name: Testando action

on:
  workflow_dispatch:

jobs:
  extract-variables:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Action with example YAML
      uses: fean-developer/github-action-python@v2.0.2
      with:
        yaml_file: 'config.yaml'
        prefix: 'AXWAY_'

    - name: Run groups messages
      shell: bash
      run: |
        echo "Teste exibir Group Logs :rocket:"
        echo "::group::Organizations Lista de pastas"
        echo "Listando todas as pastas" 
        ls -la
        echo "As Pastas Listadas"

        echo "Exibir arquivo config.yaml"
        cat ./config.yaml
        echo "\nFim do arquivo"

        echo "::endgroup::"
        
