name: Testando action

on:
  workflow_dispatch:

jobs:
  build:
    using: 'docker'
    image: 'Dockerfile'  # Defina as versões do Node.js que você quer testar
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Action with example YAML
        uses: fean-developer/gha-typescript@GHA-TS-001
        with:
          config_file: 'config.yaml'
          prefix: 'AXWAY_'
        
        
