name: Testando action

on:
  workflow_dispatch:

jobs:
  extract-variables:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: $ {{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
    
      - name: Install dependecies
        run: npm ci

      - name: Build
        run: npm rum build

      - name: Run Action with example YAML
        uses: fean-developer/gha-typescript@GHA-TS-001
        with:
          yaml_file: 'config.yaml'
          prefix: 'AXWAY_'
        
        
